author: me@oxysocks.com
description: Web API for domotica use in Go

filesets:
    includes:
        - templates
        - public
        - README.md
        - LICENSE
    excludes:
        - \.git
    depth: 3